//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baraa.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Baraa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Baraa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Baraa.UI.Resources.Baraa", typeof(Baraa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Confirm.
        /// </summary>
        public static string Alert_Confirm {
            get {
                return ResourceManager.GetString("Alert_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string CancelledMessage {
            get {
                return ResourceManager.GetString("CancelledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Country.
        /// </summary>
        public static string Choose_Country {
            get {
                return ResourceManager.GetString("Choose_Country", resourceCulture);
            }
        }
        public static string Choose_City
        {
            get
            {
                return ResourceManager.GetString("Choose_City", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Choose Role.
        /// </summary>
        public static string Choose_Role {
            get {
                return ResourceManager.GetString("Choose_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose User.
        /// </summary>
        public static string Choose_User {
            get {
                return ResourceManager.GetString("Choose_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name En.
        /// </summary>
        public static string Country_NameEN {
            get {
                return ResourceManager.GetString("Country_NameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string Enter_Password {
            get {
                return ResourceManager.GetString("Enter_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Pasword.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Setting
        {
            get
            {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Agent
        {
            get
            {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Name_Ar
        {
            get
            {
                return ResourceManager.GetString("Name_Ar", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Name_En
        {
            get
            {
                return ResourceManager.GetString("Name_En", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string First_Mob
        {
            get
            {
                return ResourceManager.GetString("First_Mob", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Sec_Mob
        {
            get
            {
                return ResourceManager.GetString("Sec_Mob", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Choose_Zone
        {
            get
            {
                return ResourceManager.GetString("Choose_Zone", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string fax
        {
            get
            {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AddressEn
        {
            get
            {
                return ResourceManager.GetString("AddressEn", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string First_Mail
        {
            get
            {
                return ResourceManager.GetString("First_Mail", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Sec_Mail
        {
            get
            {
                return ResourceManager.GetString("Sec_Mail", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string WebZSite
        {
            get
            {
                return ResourceManager.GetString("WebZSite", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Manager_Name
        {
            get
            {
                return ResourceManager.GetString("Manager_Name", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Courier_Delivery_Price
        {
            get
            {
                return ResourceManager.GetString("Courier_Delivery_Price", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string save
        {
            get
            {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AddressAr
        {
            get
            {
                return ResourceManager.GetString("AddressAr", resourceCulture);
            }
        }

    }
}
